import React from 'react'
import ReactDOM from 'react-dom'

import SearchBar from './components/search_bar'

const API_KEY = 'AIzaSyBY3M8hXITyiog4ZPSurktkgawjG-fCHJE'

// create a new component. Component should produce HTML
const App = () => {
  return <div>
    <SearchBar />
  </div>
}
// take component html generated by react and insert into page (dom)
ReactDOM.render(<App />, document.querySelector('.container'))
